### ISSUE TITLE
Does list_journals.py pick up mycological journals?

### ISSUE THREAD

**Issue by qgroom** [AgentschapPlantentuinMeise/TETTRIs-mapping-taxonomists#11]
Might mycological journals be missed by list_journals.py?
Perhaps also bryological and phycological journals.

**Comment by melanie-de-nolf** [comment]
The script picks up bryological journals that have "taxonomy" or something similar associated as a subject on Wikidata, or as a concept on OpenAlex. Phycological journals seem to mostly not be picked up this way, but "taxonomy" could be added as a subject on Wikidata.
