### ISSUE TITLE
File crop wild relatives.tsv is missing

### ISSUE THREAD

**Issue by qgroom** [AgentschapPlantentuinMeise/TETTRIs-mapping-taxonomists#18]
Could we either add the file called `crop wild relatives.tsv` to the repo, or give the instructions for making it?

**Comment by qgroom** [comment]
Perhaps the same data, but in a different format is used as `file crop wild relatives.xlsx`. Can this file be provided, or perhaps we can replace it with `crop wild relatives.tsv`

**Comment by melanie-de-nolf** [comment]
The `xlsx` file is the input data, the tsv (or csv) used to be the output of a script. This output was used to make a heattree with `Krona.xltm` if I recall correctly. The updated script doesn't make a `crop wild relatives.tsv` anymore, but a shared `supply_and_demand_order_level.tsv` with all processed demand data combined. This is used to make a heattree with the `heattree.R` script. The scripts have been updated and I will add the sources of the input data and some information in the readme.
