### ISSUE TITLE
paging

### ISSUE THREAD

**Issue by qgroom** [AgentschapPlantentuinMeise/TETTRIs-mapping-taxonomists#2]
When you pull data from OpenAlex you use a page length of 200, but you don't use paging.
You get away with this because it only pulls back 161 lines. However, there is a big danger in future runs that you will pull back 200 hundred rows and you won't notice that you are loosing data.
If you don't want to implement paging yet, it would be good to introduce a trap so that if you retrieve the same number of rows of the page length, the script should warm you that there might be a problem.

**Comment by qgroom** [comment]
I should have said. This refers to `1-1 Replicating RLIT methodology with OpenAlex.ipynb`

**Comment by qgroom** [comment]
@melanie-de-nolf can you give an update on this. Perhaps this issue can be closed

**Comment by melanie-de-nolf** [comment]
All requests from the OpenAlex API are now made with functions from the `download.py` (`request_works` and `request_sources`) and these functions include paging
