### ISSUE TITLE
it is not clear how file journals_cumulative_path.txt is made

### ISSUE THREAD

**Issue by qgroom** [AgentschapPlantentuinMeise/TETTRIs-mapping-taxonomists#20]
scripts `cumulative.py` and `TETTRIs-mapping-taxonomists\src\data\gender.py` both require the file `journals_cumulative_path.txt` as input, but it is not clear how this file is created or where it comes from.

**Comment by melanie-de-nolf** [comment]
`cumulative.py` makes `journals_cumulative_path.txt`. I added some clarification in the comments
